### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [collective/collective.js.fullcalendar#4]
@simahawk @tdesvenain Is it possible to make a new release ?
Or to give me rights on Pypi to do so (user : laz) ?

Thank you !

**Comment by laulaz** [comment]
Or maybe @vincentfretin ?

Thanks  👍

**Comment by laulaz** [comment]
Please check / merge #5 if possible before releasing this ...

**Comment by simahawk** [comment]
@laulaz I added you as maintainer.

**Comment by laulaz** [comment]
Release done, thanks a lot @simahawk !
